// ─── Semantic Model types ─────────────────────────────────────────────────────

export type {
  AppendSemanticModelSourcesRequest,
  AppendSemanticModelSourcesResponse,
  BackfillLegacySemanticModelSourcesResponse,
  CheckSemanticModelSourceExistenceRequest,
  CheckSemanticModelSourceExistenceResponse,
  ColumnPreferenceSpec,
  CreateEmptySemanticModelRequest,
  CreateEmptySemanticModelResponse,
  CreateSemanticModelSegmentRequest,
  CreateSemanticEntryRequest,
  CreateSemanticModelWithSourcesRequest,
  CreateSemanticModelWithSourcesResponse,
  DeleteSemanticModelSegmentRequest,
  DimensionSpec,
  ExportSemanticModelResponse,
  FactSpec,
  GetSemanticModelSourceDocumentRequest,
  GlossarySpec,
  ImportSemanticModelRequest,
  ImportSemanticModelResponse,
  ImportInitialSemanticModelSegmentsRequest,
  PreviewSemanticModelSourceSelectionsRequest,
  PreviewSemanticModelSourceSelectionsResponse,
  InjectionStage,
  JoinColumnPair,
  KnowledgeBaseDataDomain,
  KnowledgeBaseSourceJob,
  KnowledgeBaseSourceJobRun,
  LogicTextSpec,
  MetricSpec,
  NamedFilterSpec,
  RelationshipSpec,
  SemanticEntry,
  SemanticEntryListParams,
  SemanticEntryListResponse,
  SemanticEntrySpec,
  SemanticKind,
  SemanticModelDatabaseTableSourceSelection,
  SemanticModelCreateSource,
  SemanticModelCreateSourceType,
  SemanticModel,
  SemanticModelArtifactPreviewOptions,
  SemanticModelArtifactPreviewResponse,
  SemanticModelFilePreviewOptions,
  SemanticModelFilePreviewResponse,
  SemanticModelCreateResponse,
  SemanticModelFiles,
  SemanticModelImageIndexConfig,
  SemanticModelImageIndexFileStatus,
  SemanticModelListRequest,
  SemanticModelListResponse,
  SemanticModelMutationResponse,
  SemanticModelTagListResponse,
  SemanticModelTagStat,
  SemanticModelDocumentSegment,
  SemanticModelSourceCounts,
  SemanticModelSource,
  SemanticModelSourceSelection,
  SemanticModelSourceSelectionFilters,
  SemanticModelSourceDocument,
  SemanticModelSourceFileInfo,
  SemanticModelSourceIngestStatus,
  SemanticModelSourceJobListResponse,
  SemanticModelSourceListRequest,
  SemanticModelSourceListResponse,
  SemanticModelSourcePreview,
  SemanticModelSourceSubmitPayload,
  SemanticModelSourceType,
  SemanticModelVolumeFileSourceSelection,
  SemanticModelTable,
  SemanticModelUpdateRequest,
  SemanticModelUpsertRequest,
  SemanticModelSegment,
  SemanticModelSegmentMutationBase,
  SemanticModelSegmentMutationResult,
  SemanticModelSegmentStatus,
  SemanticModelSegmentVersion,
  SemanticMutationResponse,
  SemanticPagedResponse,
  ReembedSemanticModelSegmentsRequest,
  ReconcileSemanticModelSourceJobsResponse,
  SetCurrentSemanticModelSegmentVersionRequest,
  UpdateSemanticEntryRequest,
  UpdateSemanticModelSourceGovernanceRequest,
  UpdateSemanticModelSourceGovernanceResponse,
  UpdateSemanticModelSegmentEnabledRequest,
  UpdateSemanticModelSegmentRequest,
  UploadSemanticModelLocalFileResponse,
  ValidateSemanticModelResponse,
  VerifiedQuerySpec,
} from './semantic.types';

// ─── Semantic Model API functions ─────────────────────────────────────────────

export {
  appendSemanticModelSourcesApi,
  backfillLegacySemanticModelSourcesApi,
  checkSemanticModelSourceExistenceApi,
  createSemanticModelSegmentApi,
  createSemanticEntryApi,
  createSemanticModelApi,
  createEmptySemanticModelApi,
  createSemanticModelWithSourcesApi,
  deleteSemanticModelSegmentApi,
  deleteSemanticEntryApi,
  deleteSemanticModelApi,
  deleteSemanticModelSourceApi,
  exportSemanticModelApi,
  getSemanticModelApi,
  getSemanticModelSourceDocumentApi,
  importSemanticModelApi,
  importInitialSemanticModelSegmentsApi,
  listSemanticEntriesApi,
  listSemanticModelSourceJobsApi,
  listSemanticModelSourcesApi,
  listSemanticModelTagsApi,
  listSemanticModelsApi,
  previewSemanticModelArtifactApi,
  previewSemanticModelSourceFileApi,
  previewSemanticModelSourceSelectionsApi,
  reconcileSemanticModelSourceJobsApi,
  reembedSemanticModelSegmentsApi,
  setCurrentSemanticModelSegmentVersionApi,
  updateSemanticEntryApi,
  updateSemanticModelApi,
  updateSemanticModelSegmentApi,
  updateSemanticModelSegmentEnabledApi,
  updateSemanticModelSourceGovernanceApi,
  uploadSemanticModelLocalFileApi,
  validateSemanticModelApi,
} from './semantic';

// ─── Table types ──────────────────────────────────────────────────────────────

export type {
  GetTableColumnsRequest,
  GetTableColumnsResponse,
  ListDatabaseTablesRequest,
  ListDatabaseTablesResponse,
  TableOverviewItem,
  TableOverviewResponse,
} from './table.types';

// ─── Table API functions ──────────────────────────────────────────────────────

export { getTableColumnsApi, listDatabaseTablesApi, getTableOverviewApi } from './table';
